### ISSUE TITLE
--tls-noverify doesn't work

### ISSUE THREAD

**Issue by slingamn** [ergochat/ircdog#10]
[redacted, see below]

**Comment by DanielOaks** [comment]
Ah. --tls-noverify doesn't imply --tls at the moment.

If the user uses --tls-noverify, we should manually enable --tls in the arguments map as well. Thanks!

**Comment by slingamn** [comment]
Makes sense --- or keep the existing functionality, but rename it to `--noverify`.

**Comment by slingamn** [comment]
4db2e808
