### ISSUE TITLE
Websocket server

### ISSUE THREAD

**Issue by DanielOaks** [ergochat/ircdog#14]
Requested: 

> dan-: would you be up for adding a ever-so-basic websocket server into ircdog so that this html age can tap into it also? literally all it needs is the raw irclines dumping down the websocket and nothing more
> would be cool to have both things working in a similar way on that front so we can be improving the same ui for debugging stuff
> **dan->** yeah wouldn't mind at all prawnsalad, I'd just have it be activated via a --param or something
> **dan->** I'm not too familiar with websocket particulars but I'd assume just dump utf-8 text 'messages' or whatever how kiwi's existing one works would be fine for your needs?
> **dan->** (alt is doing the binary dumping like unreal does)
> dan-: it sends the irc lines as json objects, but pretty much yea. eg:
```c
{act: 'connection', type: 'open', start: Date.now()}
{act: 'data', data: {fromServer:false, data:'join #foo', ts: Date.now()}}
```
> i also have it caching all of those messages so that when the page connects, it just dumps the cache down the websocket so it always has a complete session

**Comment by slingamn** [comment]
Added websocket client support in #24. For other use cases, https://github.com/ergochat/webircproxy has a debug mode.
