### ISSUE TITLE
Implement shell-style command history

### ISSUE THREAD

**Issue by examknow** [ergochat/ircdog#19]
I tend to typo a lot so it would be extremely useful if I could just press my up arrow like I would on my shell or on my normal IRC client to get the command back.

**Comment by DanielOaks** [comment]
yeah I wanna do this, see also #12, the main issues with tackling this are:

- making sure it still works on Windows (iirc I had some trouble getting windows compatibility while also implementing this sort of gui. maybe that's better now though).
- getting the 16-99 control codes working properly (we're gonna have to send our own ANSI, and this feels like a more complicated thing than doing the shell-style message typing/entry so I sorta want to tackle it first if I can).

**Comment by slingamn** [comment]
Moved to #28
