### ISSUE TITLE
Record raw traffic to file

### ISSUE THREAD

**Issue by DanielOaks** [ergochat/ircdog#2]
Ingoing and outgoing. Prolly some explicit line markings before each line when saving it like:

```
 -> NICK dn
 -> USER d d d d
<-  001 lol etc
```

**Comment by slingamn** [comment]
Perhaps `--echo` to print a local echo of input, with the arrow marker? Then this could be accomplished with `ircdog | tee out.txt`

**Comment by slingamn** [comment]
Actually, that's pointless, this should just be a separate `--transcript=<file>` arg.
