### ISSUE TITLE
Feature request: "You're connected" indicator

### ISSUE THREAD

**Issue by lopcode** [ergochat/ircdog#5]
I'm testing [Burrow](https://github.com/willowchat/burrow), and noticed that there's no indication that you're connected. I think most servers send you something like "Looking up your hostname" messages which makes it more obvious.

A little message saying you're connected might be helpful. I've attached a screenshot of a successful connection to a testnet, with no messages.

<img width="414" alt="screen shot 2017-12-29 at 12 30 37" src="https://user-images.githubusercontent.com/149851/34437201-340dea78-ec94-11e7-8c95-d7ae37c8d8ed.png">

**Comment by DanielOaks** [comment]
Hmm, this is an interesting one for sure. I think waiting for just a moment and then displaying our own "Connected!" message if none comes from the server would work pretty decently. Kinda wanna keep ircdog relatively light, always printing a *Connected!* message feels a little strange.

I'll play around with it, might not be that bad once I try it out for realsies. Thanks very much for the suggestion!

**Comment by slingamn** [comment]
If we get readline support (#28), the prompt won't display until we successfully connect to the remote, which will help somewhat.

We might also consider a verbose mode (compare netcat).

**Comment by jesopo** [comment]
for reference, netcat's behaviour:

```
✨ ~ % nc irc.libera.chat 6667
:cadmium.libera.chat NOTICE * :*** Checking Ident
:cadmium.libera.chat NOTICE * :*** Looking up your hostname...
:cadmium.libera.chat NOTICE * :*** Found your hostname: husky.lolnerd.net
^C
✨ ~ % nc irc.libera.chat 6667 -v
Connection to irc.libera.chat (2001:470:1:dea::95) 6667 port [tcp/ircd] succeeded!
:cadmium.libera.chat NOTICE * :*** Checking Ident
:cadmium.libera.chat NOTICE * :*** Looking up your hostname...
:cadmium.libera.chat NOTICE * :*** Found your hostname: husky.lolnerd.net
```

**Comment by slingamn** [comment]
Yeah, that's similar to what we print unconditionally in --listen mode:

https://github.com/ergochat/ircdog/blob/dd3d41b84e2b44a063735190571b039a06e4ca93/ircdog.go#L417

I'm sold, let's get a verbose mode.

**Comment by slingamn** [comment]
Added --verbose in 8e33735f54e4ec779156e46dd4fd69a7e77c3fc6
