### ISSUE TITLE
Feature request: hide PINGs

### ISSUE THREAD

**Issue by lopcode** [ergochat/ircdog#6]
For servers which preemptively ping clients, the log rapidly gets filled with PING & PONG requests and replies.

It might be helpful to have a flag to hide them. Probably should be visible by default, though. Perhaps some sort of configurable hiding with lists, like `--hide PING,PONG`.

**Comment by DanielOaks** [comment]
Yeah I could definitely see something like this, thanks for the request

**Comment by DanielOaks** [comment]
Implemented by abf16cb7fc6762f76dd2dcf64d0d65f93b8aef23, will be in the next release. Thanks again for the suggestion!

**Comment by DanielOaks** [comment]
Which is the v0.2.0 release [right here](https://github.com/goshuirc/ircdog/releases/)! Feel free to let me know if it doesn't act as expected :)
